version: '3'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/web

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:3000
    volumes:
      - ./nginx:/web
